workflows:
  android-app:
    name: Android SMS Gateway
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Setup Gradle
        script: |
          # Local properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          
          # Settings gradle
          echo 'rootProject.name = "SMSGateway"' > settings.gradle
          echo 'include ":app"' >> settings.gradle
          
          # Root build.gradle
          echo 'buildscript {' > build.gradle
          echo '    repositories {' >> build.gradle
          echo '        google()' >> build.gradle
          echo '        mavenCentral()' >> build.gradle
          echo '    }' >> build.gradle
          echo '    dependencies {' >> build.gradle
          echo '        classpath "com.android.tools.build:gradle:7.4.2"' >> build.gradle
          echo '        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"' >> build.gradle
          echo '    }' >> build.gradle
          echo '}' >> build.gradle
          echo 'allprojects {' >> build.gradle
          echo '    repositories {' >> build.gradle
          echo '        google()' >> build.gradle
          echo '        mavenCentral()' >> build.gradle
          echo '    }' >> build.gradle
          echo '}' >> build.gradle
          
          # App build.gradle
          mkdir -p app
          cat > app/build.gradle << 'EOL'
          apply plugin: 'com.android.application'
          apply plugin: 'kotlin-android'
          
          android {
              compileSdkVersion 33
              defaultConfig {
                  applicationId "com.example.smsgateway"
                  minSdkVersion 24
                  targetSdkVersion 33
                  versionCode 1
                  versionName "1.0"
              }
          }
          
          dependencies {
              implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0"
              implementation 'androidx.core:core-ktx:1.9.0'
          }
          EOL
          
          # Gradle wrapper
          mkdir -p gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          mv gradle-7.6 gradle-dist
          echo '#!/bin/sh' > gradlew
          echo 'exec gradle-dist/bin/gradle "$@"' >> gradlew
          chmod +x gradlew
          
          echo 'distributionBase=GRADLE_USER_HOME' > gradle/wrapper/gradle-wrapper.properties
          echo 'distributionPath=wrapper/dists' >> gradle/wrapper/gradle-wrapper.properties
          echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip' >> gradle/wrapper/gradle-wrapper.properties
          echo 'zipStoreBase=GRADLE_USER_HOME' >> gradle/wrapper/gradle-wrapper.properties
          echo 'zipStorePath=wrapper/dists' >> gradle/wrapper/gradle-wrapper.properties
      
      - name: Build Android app
        script: |
          ./gradlew clean
          ./gradlew assembleDebug --info
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
