workflows:
  android-app:
    name: Android SMS Gateway
    max_build_duration: 60
    environment:
      groups:
        - android_config
      vars:
        PACKAGE_NAME: "com.example.smsgateway"
      java: 17
    scripts:
      - name: Show environment info
        script: |
          java -version
          echo "Android SDK Root: $ANDROID_SDK_ROOT"
          echo "Working directory: $(pwd)"
          ls -la
          
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
          cat local.properties
          
      - name: Setup Gradle
        script: |
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip gradle-8.2-bin.zip
          mv gradle-8.2 gradle
          mkdir -p gradle/wrapper
          echo "#!/bin/sh" > gradlew
          echo 'exec gradle/bin/gradle "$@"' >> gradlew
          chmod +x gradlew
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          ls -la gradle/wrapper
          ./gradlew --version
          
      - name: Build Android debug app
        script: |
          ./gradlew clean --info
          ./gradlew assembleDebug --info --stacktrace
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/*
