workflows:
  android-app:
    name: Android SMS Gateway
    max_build_duration: 60
    environment:
      groups:
        - android_config
      vars:
        PACKAGE_NAME: "com.example.smsgateway"
      java: 17
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
          
      - name: Download Gradle wrapper
        script: |
          mkdir -p gradle/wrapper
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip -P gradle/wrapper/
          
      - name: Set Gradle permissions
        script: |
          chmod +x ./gradlew
          
      - name: Build Android debug app
        script: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
